apiVersion: v1

kind: PersistentVolume

metadata:

  name: pv-www

spec:

  storageClassName: standard

  accessModes:

    - ReadWriteOnce

  capacity:

    storage: 2Gi

  hostPath:

    path: /www/
