apiVersion: v1

kind: PersistentVolumeClaim

metadata:

  name: pvc-www
  labels:
    # insert any desired labels to identify your claim
    app: test

spec:
  storageClassName: standard
  volumeName: pv-www

  accessModes:

    - ReadWriteOnce

  resources:

    requests:

      storage: 2Gi
